apiVersion: skaffold/v2beta18
kind: Config
profiles:
  - name: local
    build:
      local:
        push: true
        useDockerCLI: true
      artifacts:
        - image: edu10
    deploy:
      kubectl:
        manifests:
          - k8s/local/edu.yaml
    portForward:
      - resourceType: Service
        resourceName: edu10-svc
        namespace: edu-app
        port: 8080
        localPort: 9001 # *Optional*

  - name: dev
    build:
      local:
        push: true
      artifacts:
        - image: edu10
          jib:
            args:
              - -DskipTests
              - "-Dgs ${maven_settings}"
              - "-Djib.container.environment=SPRING_PROFILES_ACTIVE=dev"
            fromImage: openjdk:17-alpine
